import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
    title: "News Paper Category Bangladesh Page",
    description: "Generated by create next app",
};

export default function CategorybangladeshLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
                {children}
            <Footer />
        </>
                
    );
}
