import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "../globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

const notoSerifBengali = Noto_Serif_Bengali({
    variable: "--font-noto-serif-bengali",
    subsets: ["bengali"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "News Paper Archive Page",
    description: "Generated by create next app",
};

export default function ArchiveLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
            <>
                <Header />
                {children}
                <Footer />
            </>
    );
}
